#!/usr/bin/env ruby

ENV['RUBY_ENV'] = 'test'
require 'rdm'

REVISION = ARGV.clone.first
PATH     = File.expand_path(__FILE__)

Rdm.root(__FILE__)

begin
  changed_packages = Rdm::Handlers::DiffPackageHandler.handle(
    path:     PATH, 
    revision: REVISION
  )

  puts "Tests for the following packages will run:"
  puts changed_packages

  changed_packages.each do |package| 
    Rdm::SpecRunner.run(
      package:               package,
      path:                  PATH,
      skip_ignored_packages: false,
      show_missing_packages: true
    )
  end
  

rescue Rdm::Errors::GitRepositoryNotInitialized
  puts "Git repository is not initialized. Use `git init .`"
  exit(1)
end


