#!/usr/bin/env ruby

## # run own tests:
## $ TEST_RUN=1 tests/run

## # run application tests:
## $ tests/run

## # run package tests:
## $ tests/run commands

## # run spec in a package:
## $ tests/run commands some_spec.rb

ENV['RUBY_ENV'] = 'test'
require 'rdm'

if ENV['TEST_RUN']
  require 'minitest/autorun'
  describe Rdm::SpecRunner::Runner do
    before do
      @runner = Rdm::SpecRunner::Runner.new({})
    end

    describe 'works ' do
      it 'assert true' do
        assert 2 == 2
      end
    end
  end
else
  Rdm::SpecRunner.run
end
