source 'https://rubygems.org'

gem 'rdm',  require: false

# gem 'smart_ioc',      require: false

group :test do
  gem 'rspec',  '3.5.0',   require: false
  gem 'byebug', '9.0.6',   require: false
end
